package com.example.budget_management_app.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    INTERNAL_EXCEPTION("INTERNAL_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),
    EMAIL_SEND_FAIL("EMAIL_SEND_FAIL", HttpStatus.INTERNAL_SERVER_ERROR),
    STORAGE_ERROR("STORAGE_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),

    NOT_FOUND("NOT_FOUND", HttpStatus.NOT_FOUND),
    USER_NOT_FOUND("USER_NOT_FOUND", HttpStatus.NOT_FOUND),

    INVALID_TOKEN("INVALID_TOKEN", HttpStatus.UNAUTHORIZED),
    TOKEN_NOT_FOUND("TOKEN_NOT_FOUND", HttpStatus.UNAUTHORIZED),
    CODE_EXPIRED("CODE_EXPIRED", HttpStatus.UNAUTHORIZED),
    INVALID_CODE("INVALID_CODE", HttpStatus.UNAUTHORIZED),

    USER_NOT_ACTIVE("USER_NOT_ACTIVE", HttpStatus.FORBIDDEN),
    MFA_CONFIGURATION("MFA_CONFIGURATION", HttpStatus.FORBIDDEN),

    EMAIL_ALREADY_USED("EMAIL_ALREADY_USED", HttpStatus.CONFLICT),
    NAME_ALREADY_USED("NAME_ALREADY_USED", HttpStatus.CONFLICT),
    WRONG_CATEGORY_TYPE("WRONG_CATEGORY_TYPE", HttpStatus.CONFLICT),
    STATUS_ALREADY_SET("STATUS_ALREADY_SET", HttpStatus.CONFLICT),
    TRANSACTION_IS_RECURRING("TRANSACTION_IS_RECURRING", HttpStatus.CONFLICT),
    TRANSACTION_TYPE_MISMATCH("TRANSACTION_TYPE_MISMATCH", HttpStatus.CONFLICT),
    CATEGORY_IS_IN_USE("CATEGORY_IS_IN_USE", HttpStatus.CONFLICT),
    MODIFY_BUDGET_WITH_TRANSACTIONS("MODIFY_BUDGET_WITH_TRANSACTIONS", HttpStatus.CONFLICT),

    WRONG_CURRENCY("WRONG_CURRENCY", HttpStatus.BAD_REQUEST),
    WRONG_BUDGET_TYPE("WRONG_BUDGET_TYPE", HttpStatus.BAD_REQUEST),
    WRONG_TYPE("WRONG_TYPE", HttpStatus.BAD_REQUEST),
    INVALID_BUDGET_ALERT_RELATION("INVALID_BUDGET_ALERT_RELATION", HttpStatus.BAD_REQUEST),
    INACTIVE_ACCOUNT("INACTIVE_ACCOUNT", HttpStatus.BAD_REQUEST),
    INVALID_OLD_PASSWORD("INVALID_OLD_PASSWORD", HttpStatus.BAD_REQUEST),
    PASSWORDS_NOT_MATCH("PASSWORDS_NOT_MATCH", HttpStatus.BAD_REQUEST),
    USER_NOT_PENDING_DELETION("USER_NOT_PENDING_DELETION", HttpStatus.BAD_REQUEST),
    DELETE_DEFAULT_ACCOUNT("DELETE_DEFAULT_ACCOUNT", HttpStatus.BAD_REQUEST),
    DELETE_ACTIVE_ACCOUNT("DELETE_ACTIVE_ACCOUNT", HttpStatus.BAD_REQUEST),
    INVALID_RESOURCE_PATH("INVALID_RESOURCE_PATH",HttpStatus.BAD_REQUEST),
    STORAGE_VALIDATION_ERROR("STORAGE_VALIDATION_ERROR", HttpStatus.BAD_REQUEST),
    MODIFY_DEFAULT_CATEGORY("MODIFY_DEFAULT_CATEGORY", HttpStatus.BAD_REQUEST);


    private final String errorCode;
    private final HttpStatus status;
}
