SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.accounts (
    alert_threshold double precision,
    balance numeric(38,2) NOT NULL,
    budget numeric(38,2),
    include_in_total_balance boolean NOT NULL,
    is_default boolean NOT NULL,
    total_expense numeric(38,2) NOT NULL,
    total_income numeric(38,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    account_status character varying(255) NOT NULL,
    account_type character varying(255) NOT NULL,
    budget_type character varying(255) NOT NULL,
    currency character varying(255) NOT NULL,
    description character varying(255),
    icon_key character varying(255),
    name character varying(255) NOT NULL,
    CONSTRAINT accounts_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = 'PERSONAL'::text)),
    CONSTRAINT accounts_budget_type_check CHECK (((budget_type)::text = ANY ((ARRAY['WEEKLY'::character varying, 'MONTHLY'::character varying, 'NONE'::character varying])::text[]))),
    CONSTRAINT accounts_currency_check CHECK (((currency)::text = ANY ((ARRAY['PLN'::character varying, 'USD'::character varying, 'GBP'::character varying, 'EUR'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO postgres;


ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.categories (
    is_default boolean NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    icon_key character varying(255),
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT categories_type_check CHECK (((type)::text = ANY ((ARRAY['INCOME'::character varying, 'EXPENSE'::character varying, 'GENERAL'::character varying])::text[])))
);


ALTER TABLE public.categories OWNER TO postgres;


ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.chat_memory (
    conversation_id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id bigint NOT NULL,
    description character varying(256),
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    last_usage timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.chat_memory OWNER TO postgres;


CREATE TABLE public.notifications (
    is_read boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    message character varying(500) NOT NULL,
    target_url character varying(255),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['INFO'::character varying, 'SUCCESS'::character varying, 'WARNING'::character varying, 'ERROR'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;


ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.recurring_transactions (
    amount numeric(19,2) NOT NULL,
    end_date date,
    is_active boolean NOT NULL,
    next_occurrence date NOT NULL,
    recurring_value integer NOT NULL,
    start_date date NOT NULL,
    account_id bigint NOT NULL,
    category_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    description character varying(255),
    recurring_interval character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT recurring_transactions_recurring_interval_check CHECK (((recurring_interval)::text = ANY ((ARRAY['DAY'::character varying, 'WEEK'::character varying, 'MONTH'::character varying, 'YEAR'::character varying])::text[]))),
    CONSTRAINT recurring_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['EXPENSE'::character varying, 'INCOME'::character varying])::text[])))
);


ALTER TABLE public.recurring_transactions OWNER TO postgres;


ALTER TABLE public.recurring_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recurring_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.transaction_photos (
    id bigint NOT NULL,
    key character varying(255),
    original_file_name character varying(255)
);


ALTER TABLE public.transaction_photos OWNER TO postgres;


ALTER TABLE public.transaction_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.transactions (
    amount numeric(19,2) NOT NULL,
    account_id bigint NOT NULL,
    category_id bigint NOT NULL,
    id bigint NOT NULL,
    photo_id bigint,
    recurring_transaction_id bigint,
    transaction_date timestamp(6) without time zone NOT NULL,
    description character varying(255),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT transactions_type_check CHECK (((type)::text = ANY ((ARRAY['EXPENSE'::character varying, 'INCOME'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO postgres;


ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.user_sessions (
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    last_used_at timestamp(6) with time zone,
    user_id bigint,
    device_info character varying(255),
    device_type character varying(255),
    ip_address character varying(255),
    CONSTRAINT user_sessions_device_type_check CHECK (((device_type)::text = ANY ((ARRAY['DESKTOP'::character varying, 'MOBILE'::character varying, 'TABLET'::character varying, 'UNKNOWN'::character varying])::text[])))
);


ALTER TABLE public.user_sessions OWNER TO postgres;


ALTER TABLE public.user_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.users (
    mfa_enabled boolean,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    request_close_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    temp_two_factor_secret character varying(255),
    two_factor_secret character varying(255),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING_CONFIRMATION'::character varying, 'PENDING_DELETION'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;


ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.chat_memory
    ADD CONSTRAINT chat_memory_pkey PRIMARY KEY (conversation_id);


ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.recurring_transactions
    ADD CONSTRAINT recurring_transactions_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.transaction_photos
    ADD CONSTRAINT transaction_photos_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_photo_id_key UNIQUE (photo_id);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


CREATE INDEX idx_chat_memory_user_id ON public.chat_memory USING btree (user_id);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk20w7wsg13u9srbq3bd7chfxdh FOREIGN KEY (account_id) REFERENCES public.accounts(id);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk3lnwu993pw0edtly1w8hkhb78 FOREIGN KEY (recurring_transaction_id) REFERENCES public.recurring_transactions(id);


ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT fk8klxsgb8dcjjklmqebqp1twd5 FOREIGN KEY (user_id) REFERENCES public.users(id);


ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkefxi0gyhotkt7vawnerwrbmbv FOREIGN KEY (photo_id) REFERENCES public.transaction_photos(id);


ALTER TABLE ONLY public.recurring_transactions
    ADD CONSTRAINT fkf1byxnna01ws6w75pqc652kvj FOREIGN KEY (category_id) REFERENCES public.categories(id);


ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fkghuylkwuedgl2qahxjt8g41kb FOREIGN KEY (user_id) REFERENCES public.users(id);


ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES public.users(id);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fksqqi7sneo04kast0o138h19mv FOREIGN KEY (category_id) REFERENCES public.categories(id);


ALTER TABLE ONLY public.recurring_transactions
    ADD CONSTRAINT fkswli9j7o82qgc82kbigrrv579 FOREIGN KEY (account_id) REFERENCES public.accounts(id);


